//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbsenceLevelReason
    {
        public int AbsenceLevelReasonID { get; set; }
        public string AbsenceLevel { get; set; }
        public short AbsenceReasonID { get; set; }
        public bool IsDefaultReason { get; set; }
        public System.Guid DistrictGuid { get; set; }
    
        public virtual AbsenceReason AbsenceReason { get; set; }
    }
}
