//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcadSession
    {
        public AcadSession()
        {
            this.AttendanceCalendars = new HashSet<AttendanceCalendar>();
            this.AttendanceCalendarDays = new HashSet<AttendanceCalendarDay>();
            this.BellSchedules = new HashSet<BellSchedule>();
            this.CalendarDays = new HashSet<CalendarDay>();
            this.Courses = new HashSet<Course>();
            this.DayTypes = new HashSet<DayType>();
            this.Enrollments = new HashSet<Enrollment>();
            this.Schools = new HashSet<School>();
            this.StudentAcadSessions = new HashSet<StudentAcadSession>();
            this.StudentAttendanceMinutes = new HashSet<StudentAttendanceMinute>();
            this.StudentCheckInOuts = new HashSet<StudentCheckInOut>();
            this.StudentDailyAbsences = new HashSet<StudentDailyAbsence>();
            this.Terms = new HashSet<Term>();
            this.TimeSlots = new HashSet<TimeSlot>();
            this.StudentPeriodAbsences = new HashSet<StudentPeriodAbsence>();
        }
    
        public int AcadSessionID { get; set; }
        public int SchoolID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public short AcadYear { get; set; }
        public string SchedulingModel { get; set; }
        public Nullable<short> DaysInCycle { get; set; }
        public bool IsClosed { get; set; }
        public bool AreStudentsPromoted { get; set; }
        public bool GradeBookRequiresCalculation { get; set; }
        public System.Guid RowVersion { get; set; }
        public System.Guid AcadSessionGuid { get; set; }
        public System.Guid DistrictGuid { get; set; }
        public bool IsVisibleInHomePortal { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
    
        public virtual School School { get; set; }
        public virtual ICollection<AttendanceCalendar> AttendanceCalendars { get; set; }
        public virtual ICollection<AttendanceCalendarDay> AttendanceCalendarDays { get; set; }
        public virtual ICollection<BellSchedule> BellSchedules { get; set; }
        public virtual ICollection<CalendarDay> CalendarDays { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<DayType> DayTypes { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual ICollection<School> Schools { get; set; }
        public virtual ICollection<StudentAcadSession> StudentAcadSessions { get; set; }
        public virtual ICollection<StudentAttendanceMinute> StudentAttendanceMinutes { get; set; }
        public virtual ICollection<StudentCheckInOut> StudentCheckInOuts { get; set; }
        public virtual ICollection<StudentDailyAbsence> StudentDailyAbsences { get; set; }
        public virtual ICollection<Term> Terms { get; set; }
        public virtual ICollection<TimeSlot> TimeSlots { get; set; }
        public virtual ICollection<StudentPeriodAbsence> StudentPeriodAbsences { get; set; }
    }
}
