//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityCategory
    {
        public int ActivityCategoryID { get; set; }
        public int SectionID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public byte HighScoresToDrop { get; set; }
        public byte LowScoresToDrop { get; set; }
        public System.Guid DistrictGuid { get; set; }
        public Nullable<int> GradeBookCategoryId { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
