//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceSetting
    {
        public int AttendanceSettingId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public short MissingReasonId { get; set; }
        public byte Unit { get; set; }
        public decimal AllDay { get; set; }
        public decimal HalfDay { get; set; }
        public decimal TardyDay { get; set; }
        public decimal AllPeriod { get; set; }
        public decimal HalfPeriod { get; set; }
        public decimal TardyPeriod { get; set; }
        public byte AllowTardy { get; set; }
        public Nullable<decimal> TruantAbsences { get; set; }
        public Nullable<decimal> TruantUnexcusedAbsences { get; set; }
        public Nullable<short> TardyPeriodAbsenceReasonId { get; set; }
    
        public virtual AbsenceReason AbsenceReason { get; set; }
        public virtual AbsenceReason AbsenceReason1 { get; set; }
        public virtual School School { get; set; }
    }
}
