//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceCalendarDay
    {
        public int AttendanceCalendarID { get; set; }
        public System.DateTime Date { get; set; }
        public int AcadSessionID { get; set; }
        public Nullable<decimal> Portion { get; set; }
        public Nullable<int> AllDayValue { get; set; }
        public Nullable<int> HalfDayValue { get; set; }
        public Nullable<int> TardyValue { get; set; }
        public bool InSchool { get; set; }
        public System.Guid RowVersion { get; set; }
        public System.Guid DistrictGuid { get; set; }
        public decimal Fte { get; set; }
    
        public virtual AcadSession AcadSession { get; set; }
        public virtual AttendanceCalendar AttendanceCalendar { get; set; }
    }
}
