//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceCalendar
    {
        public AttendanceCalendar()
        {
            this.AttendanceCalendarDays = new HashSet<AttendanceCalendarDay>();
            this.StudentAcadSessions = new HashSet<StudentAcadSession>();
        }
    
        public int AttendanceCalendarID { get; set; }
        public int AcadSessionID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.Guid RowVersion { get; set; }
        public System.Guid DistrictGuid { get; set; }
    
        public virtual AcadSession AcadSession { get; set; }
        public virtual ICollection<AttendanceCalendarDay> AttendanceCalendarDays { get; set; }
        public virtual ICollection<StudentAcadSession> StudentAcadSessions { get; set; }
    }
}
