//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarDay
    {
        public int AcadSessionID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> DayTypeID { get; set; }
        public Nullable<int> BellScheduleID { get; set; }
        public string Description { get; set; }
        public decimal FractionOfDay { get; set; }
        public bool InCalendar { get; set; }
        public bool InSchool { get; set; }
        public bool IsInstructional { get; set; }
        public bool IsNonMembershipDay { get; set; }
        public System.Guid RowVersion { get; set; }
        public System.Guid DistrictGuid { get; set; }
    
        public virtual AcadSession AcadSession { get; set; }
        public virtual BellSchedule BellSchedule { get; set; }
        public virtual DayType DayType { get; set; }
    }
}
