//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Course1 = new HashSet<Course>();
            this.CourseSchools = new HashSet<CourseSchool>();
            this.ScheduledSections = new HashSet<ScheduledSection>();
            this.SectionTerms = new HashSet<SectionTerm>();
            this.StudentSchedules = new HashSet<StudentSchedule>();
            this.StudentSchedules1 = new HashSet<StudentSchedule>();
            this.SectionStaffs = new HashSet<SectionStaff>();
            this.StudentPeriodAbsences = new HashSet<StudentPeriodAbsence>();
            this.ActivityCategories = new HashSet<ActivityCategory>();
        }
    
        public int CourseID { get; set; }
        public string CourseNumber { get; set; }
        public Nullable<int> SectionOfCourseID { get; set; }
        public string SectionNumber { get; set; }
        public string FullSectionNumber { get; set; }
        public Nullable<int> AcadSessionID { get; set; }
        public Nullable<int> GradingScaleID { get; set; }
        public string AltCourseNumber { get; set; }
        public string StateCourseNumber { get; set; }
        public Nullable<short> ClassInstProgramID { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public Nullable<short> MinGradeLevelID { get; set; }
        public Nullable<short> MaxGradeLevelID { get; set; }
        public short CourseTypeID { get; set; }
        public Nullable<int> PrimaryTeacherID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public string AllowedGenders { get; set; }
        public Nullable<short> DefaultStudentCapacity { get; set; }
        public Nullable<short> DifficultyLevelID { get; set; }
        public Nullable<short> TeachingMethodID { get; set; }
        public Nullable<short> FundingMethodID { get; set; }
        public Nullable<short> InstructionalSettingID { get; set; }
        public Nullable<decimal> GPACredit { get; set; }
        public Nullable<decimal> GradCredit { get; set; }
        public bool IncludeInHonorRoll { get; set; }
        public bool IsInstructionalTime { get; set; }
        public bool IsStateReported { get; set; }
        public bool DisplayOnReportCard { get; set; }
        public Nullable<short> ClassTypeId { get; set; }
        public System.Guid RowVersion { get; set; }
        public bool IsRequired { get; set; }
        public System.Guid DistrictGuid { get; set; }
        public bool Active { get; set; }
        public Nullable<int> ReportingSchoolID { get; set; }
        public bool AreFeesPosted { get; set; }
        public bool MergeRostersForAttendance { get; set; }
    
        public virtual AcadSession AcadSession { get; set; }
        public virtual GradeLevel GradeLevel { get; set; }
        public virtual GradeLevel GradeLevel1 { get; set; }
        public virtual Room Room { get; set; }
        public virtual ICollection<Course> Course1 { get; set; }
        public virtual Course Course2 { get; set; }
        public virtual ICollection<CourseSchool> CourseSchools { get; set; }
        public virtual ICollection<ScheduledSection> ScheduledSections { get; set; }
        public virtual ICollection<SectionTerm> SectionTerms { get; set; }
        public virtual ICollection<StudentSchedule> StudentSchedules { get; set; }
        public virtual ICollection<StudentSchedule> StudentSchedules1 { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual ICollection<SectionStaff> SectionStaffs { get; set; }
        public virtual CourseType CourseType { get; set; }
        public virtual ICollection<StudentPeriodAbsence> StudentPeriodAbsences { get; set; }
        public virtual ICollection<ActivityCategory> ActivityCategories { get; set; }
    }
}
