//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.People = new HashSet<Person>();
            this.Schools = new HashSet<School>();
            this.Staffs = new HashSet<Staff>();
            this.Students = new HashSet<Student>();
        }
    
        public int DocumentID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Extension { get; set; }
        public int FileSizeInKB { get; set; }
        public string MIMEType { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.Guid RowVersion { get; set; }
        public byte[] Data { get; set; }
        public System.Guid RowIdentifier { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<School> Schools { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
