//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int EnrollmentID { get; set; }
        public int StudentID { get; set; }
        public int AcadSessionID { get; set; }
        public System.DateTime ReportedTime { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public short ActionID { get; set; }
        public string ActionClass { get; set; }
        public short ReasonID { get; set; }
        public string Note { get; set; }
        public System.Guid EnrollmentGuid { get; set; }
        public System.Guid DistrictGuid { get; set; }
        public string DestinationDistrict { get; set; }
        public string DestinationSchool { get; set; }
    
        public virtual AcadSession AcadSession { get; set; }
        public virtual Student Student { get; set; }
    }
}
