//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeLevel
    {
        public GradeLevel()
        {
            this.Courses = new HashSet<Course>();
            this.Courses1 = new HashSet<Course>();
            this.SchoolGradeLevels = new HashSet<SchoolGradeLevel>();
            this.StudentAcadSessions = new HashSet<StudentAcadSession>();
            this.StudentGradeLevels = new HashSet<StudentGradeLevel>();
            this.Standards = new HashSet<Standard>();
            this.Standards1 = new HashSet<Standard>();
        }
    
        public short GradeLevelID { get; set; }
        public string Name { get; set; }
        public string StateCode { get; set; }
        public string SIFCode { get; set; }
        public string NCESCode { get; set; }
        public string Description { get; set; }
        public bool IsGradUponPromo { get; set; }
        public short Sequence { get; set; }
        public System.Guid RowVersion { get; set; }
        public System.Guid DistrictGuid { get; set; }
        public Nullable<byte> FreezeAfterTermSeq { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Course> Courses1 { get; set; }
        public virtual ICollection<SchoolGradeLevel> SchoolGradeLevels { get; set; }
        public virtual ICollection<StudentAcadSession> StudentAcadSessions { get; set; }
        public virtual ICollection<StudentGradeLevel> StudentGradeLevels { get; set; }
        public virtual ICollection<Standard> Standards { get; set; }
        public virtual ICollection<Standard> Standards1 { get; set; }
    }
}
