//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationAddress
    {
        public OrganizationAddress()
        {
            this.Schools = new HashSet<School>();
            this.Schools1 = new HashSet<School>();
        }
    
        public int OrganizationAddressID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public Nullable<short> CountyID { get; set; }
        public System.Guid DistrictGuid { get; set; }
        public Nullable<short> StateID { get; set; }
        public Nullable<short> CountryID { get; set; }
    
        public virtual ICollection<School> Schools { get; set; }
        public virtual ICollection<School> Schools1 { get; set; }
    }
}
