//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Person1 = new HashSet<Person>();
            this.PersonAddresses = new HashSet<PersonAddress>();
            this.PersonEmails = new HashSet<PersonEmail>();
            this.PersonEthnicities = new HashSet<PersonEthnicity>();
            this.StaffContacts = new HashSet<StaffContact>();
            this.PersonTelephones = new HashSet<PersonTelephone>();
        }
    
        public int PersonID { get; set; }
        public System.Guid PersonGUID { get; set; }
        public string ConversionId { get; set; }
        public string PersonNumber { get; set; }
        public string StudentNumber { get; set; }
        public string StaffNumber { get; set; }
        public string AltPersonNumber { get; set; }
        public string DisplayName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PreferredName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string SocialSecurityNumber { get; set; }
        public Nullable<short> ProperTitleID { get; set; }
        public Nullable<short> GenerationID { get; set; }
        public Nullable<short> GenderID { get; set; }
        public string GenderDescriptor { get; set; }
        public Nullable<short> EducationLevelID { get; set; }
        public Nullable<short> MaritalStatusID { get; set; }
        public Nullable<short> ReligionID { get; set; }
        public Nullable<short> ResidencyStatusID { get; set; }
        public Nullable<int> PhotographID { get; set; }
        public Nullable<int> MailingAddressID { get; set; }
        public Nullable<int> PhysicalAddressID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CountryOfResidence { get; set; }
        public string EmployerName { get; set; }
        public bool IsHomeless { get; set; }
        public System.Guid RowVersion { get; set; }
        public Nullable<int> SpouseId { get; set; }
        public System.Guid DistrictGuid { get; set; }
        public bool IsGoGreen { get; set; }
        public bool IsHispanic { get; set; }
        public Nullable<short> CountryOfResidenceID { get; set; }
        public bool RecievesAttendanceAlerts { get; set; }
        public bool RecievesDisciplineAlerts { get; set; }
        public bool RecievesGradeAlerts { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<Person> Person1 { get; set; }
        public virtual Person Person2 { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<PersonAddress> PersonAddresses { get; set; }
        public virtual ICollection<PersonEmail> PersonEmails { get; set; }
        public virtual ICollection<PersonEthnicity> PersonEthnicities { get; set; }
        public virtual Student Student { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual ICollection<StaffContact> StaffContacts { get; set; }
        public virtual ICollection<PersonTelephone> PersonTelephones { get; set; }
        public virtual Document Document { get; set; }
    }
}
