//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public int RoomID { get; set; }
        public int SchoolID { get; set; }
        public string RoomNumber { get; set; }
        public string Description { get; set; }
        public Nullable<short> StudentCapacity { get; set; }
        public Nullable<int> LocationID { get; set; }
        public System.Guid RowVersion { get; set; }
        public System.Guid DistrictGuid { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual School School { get; set; }
    }
}
