//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledSection
    {
        public int DayTypeID { get; set; }
        public int SectionID { get; set; }
        public int TimeSlotID { get; set; }
        public System.Guid DistrictGuid { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual DayType DayType { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
    }
}
