//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledTimeSlot
    {
        public int BellScheduleID { get; set; }
        public int TimeSlotID { get; set; }
        public Nullable<short> StartTime { get; set; }
        public Nullable<short> EndTime { get; set; }
        public string Description { get; set; }
        public bool IsDailyAttendancePeriod { get; set; }
        public System.Guid DistrictGuid { get; set; }
    
        public virtual BellSchedule BellSchedule { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
    }
}
