//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.AcadSessions = new HashSet<AcadSession>();
            this.AttendanceSettings = new HashSet<AttendanceSetting>();
            this.CourseSchools = new HashSet<CourseSchool>();
            this.Rooms = new HashSet<Room>();
            this.SchoolGradeLevels = new HashSet<SchoolGradeLevel>();
            this.StaffSchools = new HashSet<StaffSchool>();
            this.Students = new HashSet<Student>();
            this.Students1 = new HashSet<Student>();
            this.StudentAcadSessions = new HashSet<StudentAcadSession>();
            this.StudentSchools = new HashSet<StudentSchool>();
            this.UserSchools = new HashSet<UserSchool>();
            this.Staffs = new HashSet<Staff>();
            this.Staffs1 = new HashSet<Staff>();
        }
    
        public int SchoolID { get; set; }
        public System.Guid SchoolGUID { get; set; }
        public string SchoolNumber { get; set; }
        public string Name { get; set; }
        public Nullable<short> SchoolCategoryID { get; set; }
        public string TelephoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> MailingAddressID { get; set; }
        public Nullable<int> PhysicalAddressID { get; set; }
        public string Title1Status { get; set; }
        public string ReportedSchoolNumber { get; set; }
        public string NCESNumber { get; set; }
        public string ACTLocationCode { get; set; }
        public string SATLocationCode { get; set; }
        public Nullable<int> SchoolLogoID { get; set; }
        public string SchoolColor { get; set; }
        public bool ReportToState { get; set; }
        public bool IsPrivate { get; set; }
        public bool IsActive { get; set; }
        public System.Guid RowVersion { get; set; }
        public System.Guid DistrictGuid { get; set; }
        public Nullable<int> CourseRequestSessionID { get; set; }
    
        public virtual ICollection<AcadSession> AcadSessions { get; set; }
        public virtual AcadSession AcadSession { get; set; }
        public virtual ICollection<AttendanceSetting> AttendanceSettings { get; set; }
        public virtual ICollection<CourseSchool> CourseSchools { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual ICollection<SchoolGradeLevel> SchoolGradeLevels { get; set; }
        public virtual ICollection<StaffSchool> StaffSchools { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Student> Students1 { get; set; }
        public virtual ICollection<StudentAcadSession> StudentAcadSessions { get; set; }
        public virtual ICollection<StudentSchool> StudentSchools { get; set; }
        public virtual ICollection<UserSchool> UserSchools { get; set; }
        public virtual OrganizationAddress OrganizationAddress { get; set; }
        public virtual OrganizationAddress OrganizationAddress1 { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<Staff> Staffs1 { get; set; }
        public virtual Document Document { get; set; }
    }
}
