//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionStaff
    {
        public int SectionID { get; set; }
        public int StaffID { get; set; }
        public bool IsHighlyQualified { get; set; }
        public bool IsCertified { get; set; }
        public bool IsPrimary { get; set; }
        public Nullable<short> StaffRoleID { get; set; }
        public System.Guid DistrictGuid { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual StaffRole StaffRole { get; set; }
    }
}
