//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffContact
    {
        public int StaffID { get; set; }
        public int ContactID { get; set; }
        public short RelationshipID { get; set; }
        public string Description { get; set; }
        public System.Guid DistrictGuid { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
