//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.Courses = new HashSet<Course>();
            this.SectionStaffs = new HashSet<SectionStaff>();
            this.StaffContacts = new HashSet<StaffContact>();
            this.StaffSchools = new HashSet<StaffSchool>();
            this.Students = new HashSet<Student>();
            this.StudentCheckInOuts = new HashSet<StudentCheckInOut>();
            this.StudentSchools = new HashSet<StudentSchool>();
        }
    
        public int StaffID { get; set; }
        public System.Guid StaffGUID { get; set; }
        public string ConversionId { get; set; }
        public string StaffNumber { get; set; }
        public string AltStaffNumber { get; set; }
        public string DisplayName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PreferredName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string SocialSecurityNumber { get; set; }
        public Nullable<short> ProperTitleID { get; set; }
        public Nullable<short> GenerationID { get; set; }
        public Nullable<short> GenderID { get; set; }
        public Nullable<short> HighestDegreeEarnedID { get; set; }
        public Nullable<short> MaritalStatusID { get; set; }
        public Nullable<int> PrimarySchoolID { get; set; }
        public Nullable<short> PrimaryClassificationID { get; set; }
        public Nullable<short> ReligionID { get; set; }
        public Nullable<short> ResidencyStatusID { get; set; }
        public Nullable<int> ResidentSchoolZoneID { get; set; }
        public Nullable<int> PhotographID { get; set; }
        public Nullable<int> MailingAddressID { get; set; }
        public Nullable<int> PhysicalAddressID { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public Nullable<short> YearsExperience { get; set; }
        public string StateIDNumber { get; set; }
        public string CountryOfResidence { get; set; }
        public bool HasTenure { get; set; }
        public bool ProvidesHomeSchooling { get; set; }
        public bool IsItinerantWorker { get; set; }
        public string TelephonyPIN { get; set; }
        public string InternetPassword { get; set; }
        public bool IntegratedWithSETS { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.Guid RowVersion { get; set; }
        public System.Guid DistrictGuid { get; set; }
        public bool IsHispanic { get; set; }
        public Nullable<short> CountryOfResidenceID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Person Person { get; set; }
        public virtual School School { get; set; }
        public virtual School School1 { get; set; }
        public virtual ICollection<SectionStaff> SectionStaffs { get; set; }
        public virtual StaffClassification StaffClassification { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<StaffContact> StaffContacts { get; set; }
        public virtual ICollection<StaffSchool> StaffSchools { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<StudentCheckInOut> StudentCheckInOuts { get; set; }
        public virtual ICollection<StudentSchool> StudentSchools { get; set; }
        public virtual Document Document { get; set; }
    }
}
