//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standard
    {
        public Standard()
        {
            this.CourseStandards = new HashSet<CourseStandard>();
            this.Standard1 = new HashSet<Standard>();
        }
    
        public int StandardID { get; set; }
        public Nullable<int> ParentStandardID { get; set; }
        public Nullable<int> AssessmentStandardID { get; set; }
        public Nullable<int> AssessmentParentStandardID { get; set; }
        public int StandardSubjectID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<short> LowerGradeLevelID { get; set; }
        public Nullable<short> UpperGradeLevelID { get; set; }
        public bool IsActive { get; set; }
        public System.Guid RowVersion { get; set; }
        public System.Guid DistrictGuid { get; set; }
    
        public virtual ICollection<CourseStandard> CourseStandards { get; set; }
        public virtual GradeLevel GradeLevel { get; set; }
        public virtual GradeLevel GradeLevel1 { get; set; }
        public virtual ICollection<Standard> Standard1 { get; set; }
        public virtual Standard Standard2 { get; set; }
        public virtual StandardSubject StandardSubject { get; set; }
    }
}
