//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StiEntities : DbContext
    {
        public StiEntities()
            : base("name=StiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AbsenceLevelReason> AbsenceLevelReasons { get; set; }
        public DbSet<AbsenceReason> AbsenceReasons { get; set; }
        public DbSet<AcadSession> AcadSessions { get; set; }
        public DbSet<Address> Addresses { get; set; }
        public DbSet<AttendanceCalendar> AttendanceCalendars { get; set; }
        public DbSet<AttendanceCalendarDay> AttendanceCalendarDays { get; set; }
        public DbSet<AttendanceSetting> AttendanceSettings { get; set; }
        public DbSet<BellSchedule> BellSchedules { get; set; }
        public DbSet<CalendarDay> CalendarDays { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<CourseSchool> CourseSchools { get; set; }
        public DbSet<DayType> DayTypes { get; set; }
        public DbSet<Enrollment> Enrollments { get; set; }
        public DbSet<Ethnicity> Ethnicities { get; set; }
        public DbSet<Gender> Genders { get; set; }
        public DbSet<GradeLevel> GradeLevels { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<PersonAddress> PersonAddresses { get; set; }
        public DbSet<PersonEmail> PersonEmails { get; set; }
        public DbSet<PersonEthnicity> PersonEthnicities { get; set; }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<ScheduledBlock> ScheduledBlocks { get; set; }
        public DbSet<ScheduledSection> ScheduledSections { get; set; }
        public DbSet<ScheduledTimeSlot> ScheduledTimeSlots { get; set; }
        public DbSet<School> Schools { get; set; }
        public DbSet<SchoolGradeLevel> SchoolGradeLevels { get; set; }
        public DbSet<SectionTerm> SectionTerms { get; set; }
        public DbSet<StaffSchool> StaffSchools { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentAcadSession> StudentAcadSessions { get; set; }
        public DbSet<StudentAttendanceMinute> StudentAttendanceMinutes { get; set; }
        public DbSet<StudentCheckInOut> StudentCheckInOuts { get; set; }
        public DbSet<StudentDailyAbsence> StudentDailyAbsences { get; set; }
        public DbSet<StudentSchedule> StudentSchedules { get; set; }
        public DbSet<StudentSchool> StudentSchools { get; set; }
        public DbSet<Term> Terms { get; set; }
        public DbSet<TimeSlot> TimeSlots { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserLogin> UserLogins { get; set; }
        public DbSet<UserPassword> UserPasswords { get; set; }
        public DbSet<UserSchool> UserSchools { get; set; }
        public DbSet<OrganizationAddress> OrganizationAddresses { get; set; }
        public DbSet<SectionStaff> SectionStaffs { get; set; }
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<StaffClassification> StaffClassifications { get; set; }
        public DbSet<StaffContact> StaffContacts { get; set; }
        public DbSet<StaffRole> StaffRoles { get; set; }
        public DbSet<StudentGradeLevel> StudentGradeLevels { get; set; }
        public DbSet<PersonTelephone> PersonTelephones { get; set; }
        public DbSet<CourseType> CourseTypes { get; set; }
        public DbSet<StudentPeriodAbsence> StudentPeriodAbsences { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<ActivityCategory> ActivityCategories { get; set; }
        public DbSet<CourseStandard> CourseStandards { get; set; }
        public DbSet<Standard> Standards { get; set; }
        public DbSet<StandardSubject> StandardSubjects { get; set; }
        public DbSet<AlphaGrade> AlphaGrades { get; set; }
        public DbSet<AlternateScore> AlternateScores { get; set; }
        public DbSet<StudentScheduleTerm> StudentScheduleTerms { get; set; }
    }
}
