//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSchedule
    {
        public int StudentID { get; set; }
        public int SectionID { get; set; }
        public Nullable<int> InclusionSectionID { get; set; }
        public Nullable<int> GradingScaleID { get; set; }
        public bool IsEnrolled { get; set; }
        public System.Guid RowVersion { get; set; }
        public System.Guid DistrictGuid { get; set; }
        public Nullable<decimal> CareerTechAverage { get; set; }
        public Nullable<short> CareerTechStatusId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Course Course1 { get; set; }
        public virtual Student Student { get; set; }
    }
}
