//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSchool
    {
        public int StudentID { get; set; }
        public int SchoolID { get; set; }
        public Nullable<int> GradingScaleID { get; set; }
        public Nullable<int> CounselorID { get; set; }
        public Nullable<short> TransportMethodID { get; set; }
        public string ParkingNumber { get; set; }
        public string LockerNumber { get; set; }
        public string LockerCombination { get; set; }
        public bool IsResponsibleForLock { get; set; }
        public Nullable<decimal> DistanceFromSchool { get; set; }
        public bool ResidesOutOfSchoolZone { get; set; }
        public bool IsTitle1Eligible { get; set; }
        public bool IncludeInClassRank { get; set; }
        public Nullable<int> AMBusID { get; set; }
        public Nullable<short> AMBusStopNumber { get; set; }
        public Nullable<short> AMBusStopTime { get; set; }
        public Nullable<int> PMBusID { get; set; }
        public Nullable<short> PMBusStopNumber { get; set; }
        public Nullable<short> PMBusStopTime { get; set; }
        public System.Guid RowVersion { get; set; }
        public System.Guid DistrictGuid { get; set; }
    
        public virtual School School { get; set; }
        public virtual Student Student { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
