//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttendanceMinute
    {
        public int StudentID { get; set; }
        public int AcadSessionID { get; set; }
        public System.DateTime Date { get; set; }
        public short MinutesExpected { get; set; }
        public short MinutesAbsent { get; set; }
        public short MinutesPresent { get; set; }
        public System.Guid DistrictGuid { get; set; }
    
        public virtual AcadSession AcadSession { get; set; }
        public virtual Student Student { get; set; }
    }
}
