//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCheckInOut
    {
        public int StudentCheckInOutID { get; set; }
        public int StudentID { get; set; }
        public int AcadSessionID { get; set; }
        public System.DateTime Date { get; set; }
        public short Time { get; set; }
        public Nullable<int> TimeSlotID { get; set; }
        public string Action { get; set; }
        public Nullable<int> AdministratorID { get; set; }
        public string AbsenceLevel { get; set; }
        public short AbsenceReasonID { get; set; }
        public string AbsenceCategory { get; set; }
        public string Note { get; set; }
        public Nullable<int> OccurrenceID { get; set; }
        public System.Guid RowVersion { get; set; }
        public System.Guid DistrictGuid { get; set; }
        public bool LevelIsOther { get; set; }
    
        public virtual AbsenceReason AbsenceReason { get; set; }
        public virtual AcadSession AcadSession { get; set; }
        public virtual Student Student { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
