//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Enrollments = new HashSet<Enrollment>();
            this.StudentAcadSessions = new HashSet<StudentAcadSession>();
            this.StudentAttendanceMinutes = new HashSet<StudentAttendanceMinute>();
            this.StudentCheckInOuts = new HashSet<StudentCheckInOut>();
            this.StudentDailyAbsences = new HashSet<StudentDailyAbsence>();
            this.StudentSchedules = new HashSet<StudentSchedule>();
            this.StudentSchools = new HashSet<StudentSchool>();
            this.StudentGradeLevels = new HashSet<StudentGradeLevel>();
            this.StudentPeriodAbsences = new HashSet<StudentPeriodAbsence>();
        }
    
        public int StudentID { get; set; }
        public System.Guid StudentGUID { get; set; }
        public string ConversionId { get; set; }
        public string StudentNumber { get; set; }
        public string DisplayName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PreferredName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string SocialSecurityNumber { get; set; }
        public Nullable<int> NextYearSchoolID { get; set; }
        public Nullable<short> ProperTitleID { get; set; }
        public Nullable<short> GenerationID { get; set; }
        public Nullable<short> GenderID { get; set; }
        public string GenderDescriptor { get; set; }
        public Nullable<short> MaritalStatusID { get; set; }
        public Nullable<short> ReligionID { get; set; }
        public Nullable<short> ResidencyStatusID { get; set; }
        public Nullable<int> PhotographID { get; set; }
        public Nullable<int> MailingAddressID { get; set; }
        public string MailingAddressMultiLine { get; set; }
        public string MailingAddressSingleLine { get; set; }
        public Nullable<bool> MailingAddressIsListed { get; set; }
        public Nullable<int> PhysicalAddressID { get; set; }
        public bool ResidesOutOfDistrict { get; set; }
        public Nullable<short> LimitedEnglishID { get; set; }
        public Nullable<short> MigrantFamilyID { get; set; }
        public string BirthCertNumber { get; set; }
        public string BirthCertVerifyNumber { get; set; }
        public string Section504Qualification { get; set; }
        public string AltStudentNumber { get; set; }
        public string StateIDNumber { get; set; }
        public string CountryOfResidence { get; set; }
        public string EmployerName { get; set; }
        public bool IsHomeless { get; set; }
        public bool IsImmigrant { get; set; }
        public bool IsForeignExchange { get; set; }
        public bool IsAllowedInetAccess { get; set; }
        public bool HasMedicalAlert { get; set; }
        public bool IsGraduate { get; set; }
        public bool IsHomeSchooled { get; set; }
        public bool IsTuition { get; set; }
        public string TelephonyPIN { get; set; }
        public string InternetPassword { get; set; }
        public string TelephoneNumber { get; set; }
        public Nullable<bool> IsListed { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> OriginalEnrollmentDate { get; set; }
        public Nullable<System.DateTime> ExpectedGraduationDate { get; set; }
        public string CachedSchoolList { get; set; }
        public string SpecialInstructions { get; set; }
        public Nullable<short> SpEdStatusID { get; set; }
        public Nullable<short> PrimaryExcepID { get; set; }
        public Nullable<short> SecondaryExcepID { get; set; }
        public Nullable<System.DateTime> SpecialEducationExitDate { get; set; }
        public Nullable<short> SpecialEducationExitReasonID { get; set; }
        public Nullable<short> LeastRestEnvID { get; set; }
        public Nullable<int> CaseManagerID { get; set; }
        public Nullable<System.DateTime> EligibilityDate { get; set; }
        public Nullable<System.DateTime> ReevaluationDate { get; set; }
        public Nullable<System.DateTime> IEPBeginDate { get; set; }
        public Nullable<System.DateTime> IEPEndDate { get; set; }
        public Nullable<System.DateTime> DateEnrolledInLEA { get; set; }
        public Nullable<int> ReportingSchoolID { get; set; }
        public Nullable<short> FirstYearInUS { get; set; }
        public Nullable<System.DateTime> USLEPEntryDate { get; set; }
        public Nullable<System.DateTime> LEPExitDate { get; set; }
        public bool IntegratedWithSETS { get; set; }
        public int UserID { get; set; }
        public System.Guid RowVersion { get; set; }
        public System.Guid DistrictGuid { get; set; }
        public bool IsGoGreen { get; set; }
        public bool IsHispanic { get; set; }
        public Nullable<short> CountryOfResidenceID { get; set; }
        public Nullable<int> LocatorStudentId { get; set; }
        public Nullable<short> HomelessStatusID { get; set; }
        public Nullable<short> CohortYear { get; set; }
        public Nullable<System.DateTime> NinthGradeEntry { get; set; }
        public bool RecievesAttendanceAlerts { get; set; }
        public bool RecievesDisciplineAlerts { get; set; }
        public bool RecievesGradeAlerts { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Person Person { get; set; }
        public virtual School School { get; set; }
        public virtual School School1 { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<StudentAcadSession> StudentAcadSessions { get; set; }
        public virtual ICollection<StudentAttendanceMinute> StudentAttendanceMinutes { get; set; }
        public virtual ICollection<StudentCheckInOut> StudentCheckInOuts { get; set; }
        public virtual ICollection<StudentDailyAbsence> StudentDailyAbsences { get; set; }
        public virtual ICollection<StudentSchedule> StudentSchedules { get; set; }
        public virtual ICollection<StudentSchool> StudentSchools { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual ICollection<StudentGradeLevel> StudentGradeLevels { get; set; }
        public virtual ICollection<StudentPeriodAbsence> StudentPeriodAbsences { get; set; }
        public virtual Document Document { get; set; }
    }
}
