//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAcadSession
    {
        public int StudentID { get; set; }
        public int AcadSessionID { get; set; }
        public int SchoolID { get; set; }
        public Nullable<int> AttendanceCalendarID { get; set; }
        public Nullable<short> GradeLevelID { get; set; }
        public string GradeLevelName { get; set; }
        public string CurrentEnrollmentStatus { get; set; }
        public string LastEnrollmentActionClass { get; set; }
        public Nullable<int> HomeroomID { get; set; }
        public string HomeroomName { get; set; }
        public Nullable<short> LunchProgramID { get; set; }
        public string LunchProgramName { get; set; }
        public Nullable<short> TransportMethodID { get; set; }
        public string TransportMethodName { get; set; }
        public decimal ReportedFTE { get; set; }
        public System.Guid RowVersion { get; set; }
        public System.Guid EnrollmentRowVersion { get; set; }
        public System.Guid HomeroomRowVersion { get; set; }
        public System.Guid SchedulingRowVersion { get; set; }
        public System.Guid DistrictGuid { get; set; }
        public bool IsRetained { get; set; }
    
        public virtual AcadSession AcadSession { get; set; }
        public virtual AttendanceCalendar AttendanceCalendar { get; set; }
        public virtual GradeLevel GradeLevel { get; set; }
        public virtual School School { get; set; }
        public virtual Student Student { get; set; }
    }
}
