//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public Term()
        {
            this.SectionTerms = new HashSet<SectionTerm>();
            this.StudentScheduleTerms = new HashSet<StudentScheduleTerm>();
        }
    
        public int TermID { get; set; }
        public int AcadSessionID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string StateCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public bool AreTranscriptsPosted { get; set; }
        public string ConnectEduTerm { get; set; }
        public byte Sequence { get; set; }
        public System.Guid RowVersion { get; set; }
        public System.Guid DistrictGuid { get; set; }
        public string SIFCode { get; set; }
        public string NCESCode { get; set; }
    
        public virtual AcadSession AcadSession { get; set; }
        public virtual ICollection<SectionTerm> SectionTerms { get; set; }
        public virtual ICollection<StudentScheduleTerm> StudentScheduleTerms { get; set; }
    }
}
