//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSlot
    {
        public TimeSlot()
        {
            this.ScheduledBlocks = new HashSet<ScheduledBlock>();
            this.ScheduledSections = new HashSet<ScheduledSection>();
            this.ScheduledTimeSlots = new HashSet<ScheduledTimeSlot>();
            this.StudentCheckInOuts = new HashSet<StudentCheckInOut>();
            this.StudentPeriodAbsences = new HashSet<StudentPeriodAbsence>();
        }
    
        public int TimeSlotID { get; set; }
        public int AcadSessionID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string StateCode { get; set; }
        public short Sequence { get; set; }
        public System.Guid RowVersion { get; set; }
        public System.Guid DistrictGuid { get; set; }
    
        public virtual AcadSession AcadSession { get; set; }
        public virtual ICollection<ScheduledBlock> ScheduledBlocks { get; set; }
        public virtual ICollection<ScheduledSection> ScheduledSections { get; set; }
        public virtual ICollection<ScheduledTimeSlot> ScheduledTimeSlots { get; set; }
        public virtual ICollection<StudentCheckInOut> StudentCheckInOuts { get; set; }
        public virtual ICollection<StudentPeriodAbsence> StudentPeriodAbsences { get; set; }
    }
}
