//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.People = new HashSet<Person>();
            this.Students = new HashSet<Student>();
            this.UserLogins = new HashSet<UserLogin>();
            this.UserPasswords = new HashSet<UserPassword>();
            this.UserSchools = new HashSet<UserSchool>();
            this.Staffs = new HashSet<Staff>();
        }
    
        public int UserID { get; set; }
        public int TrusteeID { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string LoginMethod { get; set; }
        public System.Guid UserGUID { get; set; }
        public bool LockedOut { get; set; }
        public bool IsDisabled { get; set; }
        public byte AuthenticationAttempts { get; set; }
        public Nullable<System.DateTime> LastAuthenticationAttempt { get; set; }
        public bool UseADAuthentication { get; set; }
        public bool IsSystem { get; set; }
        public System.Guid DistrictGuid { get; set; }
        public Nullable<int> InFocusUserId { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<UserLogin> UserLogins { get; set; }
        public virtual ICollection<UserPassword> UserPasswords { get; set; }
        public virtual ICollection<UserSchool> UserSchools { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
