//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int UserLoginID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public System.DateTime LoginDate { get; set; }
        public string IPAddress { get; set; }
        public string DNSHostName { get; set; }
        public bool Success { get; set; }
    
        public virtual User User { get; set; }
    }
}
