//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkable.StiConnector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSchool
    {
        public int UserID { get; set; }
        public int SchoolID { get; set; }
        public System.Guid DistrictGuid { get; set; }
    
        public virtual School School { get; set; }
        public virtual User User { get; set; }
    }
}
