CREATE TYPE [dbo].[TClassAnnouncementComplex] AS TABLE(
	[Id] [int] NOT NULL,
	[Created] [datetime2](7) NOT NULL,
	[State] [int] NOT NULL,
	[Content] [nvarchar](max) NULL,
	[Title] [nvarchar](max) NULL,
	[Expires] [datetime2](7) NOT NULL,
	[Order] [int] NOT NULL,
	[Dropped] [bit] NOT NULL,
	[ClassAnnouncementTypeRef] [int] NULL,
	[SchoolYearRef] [int] NULL,
	[SisActivityId] [int] NULL,
	[IsScored] [bit] NOT NULL,
	[MaxScore] [decimal](18, 2) NULL,
	[WeightAddition] [decimal](9, 6) NULL,
	[WeightMultiplier] [decimal](9, 6) NULL,
	[MayBeDropped] [bit] NULL,
	[VisibleForStudent] [bit] NULL,
	[ClassRef] [int] NOT NULL,
	[PrimaryTeacherName] [nvarchar](max) NULL,
	[PrimaryTeacherGender] [nvarchar](max) NULL,
	[ClassName] [nvarchar](max) NULL,
	[FullClassName] [nvarchar](max) NULL,
	[MinGradeLevelId] [int] NULL,
	[MaxGradeLevelId] [int] NULL,
	[PrimaryTeacherRef] [int] NULL,
	[DepartmentId] [uniqueidentifier] NULL,
	[IsOwner] [bit] NULL,
	[Complete] [bit] NULL,
	[AllCount] [int] NULL
)
GO