CREATE TYPE [dbo].[TSchoolOption] AS TABLE (
    [Id]                                      INT           NOT NULL,
    [AllowSectionAverageModification]         BIT           NOT NULL,
    [EarliestPaymentDate]                     DATETIME2 (7) NULL,
    [NextReceiptNumber]                       INT           NULL,
    [DefaultCombinationIndex]                 INT           NULL,
    [TimeZoneName]                            NVARCHAR (32) NULL,
    [BaseHoursOffset]                         INT           NULL,
    [BaseMinutesOffset]                       INT           NULL,
    [ObservesDst]                             BIT           NULL,
    [AllowScoreEntryForUnexcused]             BIT           NOT NULL,
    [DisciplineOverwritesAttendance]          BIT           NOT NULL,
    [AllowDualEnrollment]                     BIT           NOT NULL,
    [CompleteStudentScheduleDefinition]       NVARCHAR (2)  NOT NULL,
    [AveragingMethod]                         NVARCHAR (2)  NOT NULL,
    [CategoryAveraging]                       BIT           NOT NULL,
    [StandardsGradingScaleRef]                INT           NULL,
    [StandardsCalculationMethod]              NVARCHAR (2)  NOT NULL,
    [StandardsCalculationRule]                NVARCHAR (2)  NOT NULL,
    [StandardsCalculationWeightMaximumValues] BIT           NOT NULL,
    [LockCategories]                          BIT           NOT NULL,
    [IncludeReportCardCommentsInGradebook]    BIT           NOT NULL,
    [MergeRostersForAttendance]               BIT           NOT NULL);

